// src/components/AuthForm.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <h1 class="app-title">Todoリスト</h1>
      <h2 class="form-title">{{ isLogin ? 'ログイン' : '新規登録' }}</h2>

      <form @submit.prevent="submit" class="login-form">
        <div class="form-group">
          <label for="email">メールアドレス</label>
          <input
            id="email"
            v-model="email"
            type="email"
            placeholder="example@email.com"
            required
            autocomplete="email"
          />
        </div>

        <div class="form-group">
          <label for="password">パスワード</label>
          <input
            id="password"
            v-model="password"
            type="password"
            placeholder="6文字以上"
            required
            autocomplete="current-password"
            minlength="6"
          />
        </div>

        <p v-if="errorMessage" class="error-message">{{ errorMessage }}</p>

        <button type="submit" class="btn-submit" :disabled="loading">
          <span v-if="loading" class="loading-spinner"></span>
          {{ isLogin ? 'ログイン' : '登録する' }}
        </button>
      </form>

      <button @click="toggleMode" class="btn-toggle">
        {{ isLogin ? 'アカウントをお持ちでない方はこちら' : 'すでにアカウントをお持ちの方はこちら' }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword
} from 'firebase/auth'
import { auth } from '../firebase'

const email = ref('')
const password = ref('')
const isLogin = ref(true)
const errorMessage = ref('')
const loading = ref(false)

function toggleMode() {
  isLogin.value = !isLogin.value
  errorMessage.value = ''
}

const submit = async () => {
  errorMessage.value = ''
  loading.value = true

  try {
    if (isLogin.value) {
      await signInWithEmailAndPassword(auth, email.value, password.value)
    } else {
      await createUserWithEmailAndPassword(auth, email.value, password.value)
    }
  } catch (err: unknown) {
    const code = (err as { code?: string }).code ?? ''
    errorMessage.value = getErrorMessage(code)
  } finally {
    loading.value = false
  }
}

const getErrorMessage = (code: string): string => {
  const messages: Record<string, string> = {
    'auth/user-not-found': 'メールアドレスまたはパスワードが正しくありません',
    'auth/wrong-password': 'メールアドレスまたはパスワードが正しくありません',
    'auth/invalid-credential': 'メールアドレスまたはパスワードが正しくありません',
    'auth/email-already-in-use': 'このメールアドレスはすでに使用されています',
    'auth/weak-password': 'パスワードは6文字以上にしてください',
    'auth/invalid-email': 'メールアドレスの形式が正しくありません',
    'auth/too-many-requests': 'しばらくしてから再度お試しください',
  }
  return messages[code] ?? 'エラーが発生しました。もう一度お試しください'
}
</script>

<style scoped>
.login-page {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background: #f5f5f5;
  padding: 1rem;
}

.login-card {
  background: white;
  border-radius: 12px;
  padding: 2.5rem;
  width: 100%;
  max-width: 400px;
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.1);
}

.app-title {
  text-align: center;
  font-size: 1.75rem;
  font-weight: 700;
  color: #667eea;
  margin-bottom: 0.25rem;
}

.form-title {
  text-align: center;
  font-size: 1.1rem;
  font-weight: 500;
  color: #555;
  margin-bottom: 2rem;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-group label {
  font-size: 0.875rem;
  font-weight: 500;
  color: #444;
}

.form-group input {
  padding: 0.75rem 1rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  font-size: 1rem;
  outline: none;
  transition: border-color 0.2s;
  width: 100%;
  box-sizing: border-box;
}

.form-group input:focus {
  border-color: #667eea;
}

.error-message {
  font-size: 0.875rem;
  color: #e53935;
  text-align: center;
  padding: 0.5rem;
  background: #ffebee;
  border-radius: 6px;
  margin: 0;
}

.btn-submit {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.875rem;
  background: #667eea;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
  margin-top: 0.5rem;
  width: 100%;
}

.btn-submit:hover:not(:disabled) {
  background: #5a6fd6;
}

.btn-submit:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.loading-spinner {
  width: 18px;
  height: 18px;
  border: 2px solid rgba(255, 255, 255, 0.4);
  border-top-color: white;
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
  display: inline-block;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.btn-toggle {
  display: block;
  width: 100%;
  margin-top: 1.25rem;
  padding: 0.5rem;
  background: transparent;
  border: none;
  color: #667eea;
  font-size: 0.875rem;
  cursor: pointer;
  text-align: center;
  text-decoration: underline;
}

.btn-toggle:hover {
  color: #5a6fd6;
}
</style>

// src/components/AuthForm.tsx
import { useState } from 'react'
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
} from 'firebase/auth'
import { auth } from '../firebase'

const getErrorMessage = (code: string): string => {
  const messages: Record<string, string> = {
    'auth/user-not-found': 'メールアドレスまたはパスワードが正しくありません',
    'auth/wrong-password': 'メールアドレスまたはパスワードが正しくありません',
    'auth/invalid-credential': 'メールアドレスまたはパスワードが正しくありません',
    'auth/email-already-in-use': 'このメールアドレスはすでに使用されています',
    'auth/weak-password': 'パスワードは6文字以上にしてください',
    'auth/invalid-email': 'メールアドレスの形式が正しくありません',
    'auth/too-many-requests': 'しばらくしてから再度お試しください',
  }
  return messages[code] ?? 'エラーが発生しました。もう一度お試しください'
}

export default function AuthForm() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [isLogin, setIsLogin] = useState(true)
  const [errorMessage, setErrorMessage] = useState('')
  const [loading, setLoading] = useState(false)

  const toggleMode = () => {
    setIsLogin(!isLogin)
    setErrorMessage('')
  }

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    setErrorMessage('')
    setLoading(true)
    try {
      if (isLogin) {
        await signInWithEmailAndPassword(auth, email, password)
      } else {
        await createUserWithEmailAndPassword(auth, email, password)
      }
    } catch (err: unknown) {
      const code = (err as { code?: string }).code ?? ''
      setErrorMessage(getErrorMessage(code))
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="login-page">
      <div className="login-card">
        <h1 className="app-title">Todoリスト</h1>
        <h2 className="form-title">{isLogin ? 'ログイン' : '新規登録'}</h2>

        <form onSubmit={submit} className="login-form">
          <div className="form-group">
            <label htmlFor="email">メールアドレス</label>
            <input
              id="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
              type="email"
              placeholder="example@email.com"
              required
              autoComplete="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">パスワード</label>
            <input
              id="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
              type="password"
              placeholder="6文字以上"
              required
              autoComplete="current-password"
              minLength={6}
            />
          </div>

          {errorMessage && <p className="error-message">{errorMessage}</p>}

          <button type="submit" className="btn-submit" disabled={loading}>
            {loading && <span className="loading-spinner"></span>}
            {isLogin ? 'ログイン' : '登録する'}
          </button>
        </form>

        <button onClick={toggleMode} className="btn-toggle">
          {isLogin ? 'アカウントをお持ちでない方はこちら' : 'すでにアカウントをお持ちの方はこちら'}
        </button>
      </div>
    </div>
  )
}
