// src/App.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { onAuthStateChanged, signOut, type User } from 'firebase/auth'
import {
  collection,
  addDoc,
  deleteDoc,
  updateDoc,
  doc,
  onSnapshot,
  query,
  orderBy,
  serverTimestamp,
} from 'firebase/firestore'
import { auth, db } from './firebase'
import AuthForm from './components/AuthForm'

interface TodoItem {
  id: string
  text: string
  completed: boolean
}

const SWIPE_CLOSE_THRESHOLD = 100

const TODOS_CACHE_KEY = (uid: string) => `todos_cache_${uid}`

const loadCachedTodos = (uid: string): TodoItem[] => {
  try {
    const raw = localStorage.getItem(TODOS_CACHE_KEY(uid))
    return raw ? (JSON.parse(raw) as TodoItem[]) : []
  } catch {
    return []
  }
}

const saveCachedTodos = (uid: string, items: TodoItem[]) => {
  try {
    localStorage.setItem(TODOS_CACHE_KEY(uid), JSON.stringify(items))
  } catch { /* ignore */ }
}

function usePanelSwipe(onClose: () => void) {
  const [translateY, setTranslateY] = useState(0)
  const [isDragging, setIsDragging] = useState(false)
  const [isSwipeClosing, setIsSwipeClosing] = useState(false)
  const dragStartY = useRef(0)

  const onTouchStart = (e: React.TouchEvent) => {
    dragStartY.current = e.touches[0].clientY
    setTranslateY(0)
    setIsDragging(true)
  }

  const onTouchMove = (e: React.TouchEvent) => {
    e.preventDefault()
    if (!isDragging) return
    const delta = e.touches[0].clientY - dragStartY.current
    setTranslateY(Math.max(0, delta))
  }

  const onTouchEnd = () => {
    if (translateY > SWIPE_CLOSE_THRESHOLD) {
      setIsDragging(false)
      setIsSwipeClosing(true)
      setTimeout(() => {
        setIsSwipeClosing(false)
        setTranslateY(0)
        onClose()
      }, 300)
    } else {
      setIsDragging(false)
      setTranslateY(0)
    }
  }

  const panelStyle: React.CSSProperties = isSwipeClosing
    ? { transform: 'translateY(100%)' }
    : isDragging
    ? { transform: `translateY(${translateY}px)`, transition: 'none' }
    : translateY > 0
    ? { transform: `translateY(${translateY}px)` }
    : {}

  return { panelStyle, isSwipeClosing, onTouchStart, onTouchMove, onTouchEnd }
}

export default function App() {
  const [currentUser, setCurrentUser] = useState<User | null>(null)
  const [authLoading, setAuthLoading] = useState(true)
  const [todos, setTodos] = useState<TodoItem[]>([])
  const [todosLoading, setTodosLoading] = useState(false)

  const [newTodoText, setNewTodoText] = useState('')
  const [showAddPanel, setShowAddPanel] = useState(false)

  const [showEditPanel, setShowEditPanel] = useState(false)
  const [editingTodo, setEditingTodo] = useState<TodoItem | null>(null)
  const [editTodoText, setEditTodoText] = useState('')

  const [showMenu, setShowMenu] = useState(false)
  const menuRef = useRef<HTMLDivElement>(null)

  const [notificationPermission, setNotificationPermission] = useState<NotificationPermission | 'unsupported'>('unsupported')

  const completedCount = todos.filter(t => t.completed).length
  const incompleteCount = todos.filter(t => !t.completed).length
  const progressPercent = todos.length === 0 ? 0 : Math.round((completedCount / todos.length) * 100)

  const updateBadge = useCallback((count: number) => {
    if ('setAppBadge' in navigator) {
      if (count > 0) {
        navigator.setAppBadge(count)
      } else {
        navigator.clearAppBadge()
      }
    }
  }, [])

  useEffect(() => {
    updateBadge(incompleteCount)
  }, [incompleteCount, updateBadge])

  const closeAddPanel = useCallback(() => {
    setShowAddPanel(false)
    setNewTodoText('')
  }, [])

  const closeEditPanel = useCallback(() => {
    setShowEditPanel(false)
    setEditingTodo(null)
    setEditTodoText('')
  }, [])

  const addSwipe = usePanelSwipe(closeAddPanel)
  const editSwipe = usePanelSwipe(closeEditPanel)

  useEffect(() => {
    const handleDocumentClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setShowMenu(false)
      }
    }
    document.addEventListener('click', handleDocumentClick)
    return () => document.removeEventListener('click', handleDocumentClick)
  }, [])

  useEffect(() => {
    if ('Notification' in window) {
      setNotificationPermission(Notification.permission)
    }
  }, [])

  useEffect(() => {
    let unsubscribeTodos: (() => void) | null = null

    const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user)
      setAuthLoading(false)

      if (unsubscribeTodos) {
        unsubscribeTodos()
        unsubscribeTodos = null
        setTodos([])
        setTodosLoading(false)
      }

      if (user) {
        const cached = loadCachedTodos(user.uid)
        if (cached.length > 0) setTodos(cached)
        setTodosLoading(true)

        const todosRef = collection(db, 'users', user.uid, 'todos')
        const q = query(todosRef, orderBy('createdAt', 'asc'))
        unsubscribeTodos = onSnapshot(q, (snapshot) => {
          const items = snapshot.docs.map(d => ({
            id: d.id,
            text: d.data().text as string,
            completed: d.data().completed as boolean,
          }))
          setTodos(items)
          setTodosLoading(false)
          saveCachedTodos(user.uid, items)
        })

        if ('Notification' in window && Notification.permission === 'default') {
          Notification.requestPermission().then(result => {
            setNotificationPermission(result)
          })
        }
      }
    })

    return () => {
      unsubscribeAuth()
      unsubscribeTodos?.()
      if ('clearAppBadge' in navigator) navigator.clearAppBadge()
    }
  }, [])

  const addTodo = async () => {
    if (!currentUser || newTodoText.trim() === '') return
    const text = newTodoText.trim()
    closeAddPanel()
    await addDoc(collection(db, 'users', currentUser.uid, 'todos'), {
      text,
      completed: false,
      createdAt: serverTimestamp(),
    })
  }

  const toggleTodo = async (id: string) => {
    if (!currentUser) return
    const todo = todos.find(t => t.id === id)
    if (todo) {
      await updateDoc(doc(db, 'users', currentUser.uid, 'todos', id), {
        completed: !todo.completed,
      })
    }
  }

  const deleteTodo = async (id: string) => {
    if (!currentUser) return
    await deleteDoc(doc(db, 'users', currentUser.uid, 'todos', id))
  }

  const openEditPanel = (todo: TodoItem) => {
    setEditingTodo(todo)
    setEditTodoText(todo.text)
    setShowEditPanel(true)
  }

  const updateTodo = async () => {
    if (!currentUser || !editingTodo || editTodoText.trim() === '') return
    const id = editingTodo.id
    const text = editTodoText.trim()
    closeEditPanel()
    await updateDoc(doc(db, 'users', currentUser.uid, 'todos', id), { text })
  }

  const deleteTodoAndClose = async () => {
    if (!currentUser || !editingTodo) return
    const id = editingTodo.id
    closeEditPanel()
    await deleteTodo(id)
  }

  const deleteCompletedTodos = async () => {
    if (!currentUser) return
    const completed = todos.filter(t => t.completed)
    await Promise.all(
      completed.map(t => deleteDoc(doc(db, 'users', currentUser!.uid, 'todos', t.id)))
    )
  }

  const logout = async () => {
    setShowMenu(false)
    await signOut(auth)
  }

  const openAddPanel = () => {
    setShowAddPanel(true)
    setNewTodoText('')
  }

  if (authLoading) {
    return (
      <div className="loading-screen">
        <div className="loading-spinner"></div>
      </div>
    )
  }

  if (!currentUser) {
    return <AuthForm />
  }

  const overlayVisible = (showAddPanel || showEditPanel) && !addSwipe.isSwipeClosing && !editSwipe.isSwipeClosing

  return (
    <div className="todo-app">
      <div className="sticky-top">
        <header className="app-header">
          <h1>Todoリスト</h1>
          <div className="hamburger-menu" ref={menuRef}>
            <button
              className="hamburger-btn"
              onClick={() => setShowMenu(v => !v)}
              aria-label="メニューを開く"
              aria-expanded={showMenu}
            >
              <span className="hamburger-line"></span>
              <span className="hamburger-line"></span>
              <span className="hamburger-line"></span>
            </button>
            {showMenu && (
              <div className="menu-dropdown menu-fade-enter">
                <div className="menu-account">
                  <span className="menu-account-email">{currentUser.email}</span>
                </div>
                <div className="menu-divider"></div>
                <button className="menu-logout-btn" onClick={logout}>
                  <svg className="menu-logout-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                    <polyline points="16 17 21 12 16 7"/>
                    <line x1="21" y1="12" x2="9" y2="12"/>
                  </svg>
                  ログアウト
                </button>
              </div>
            )}
          </div>
        </header>

        <div className="progress-section">
          <div className="progress-labels">
            <div className="progress-labels-left">
              {completedCount > 0 && (
                <button
                  className="delete-completed-btn"
                  onClick={deleteCompletedTodos}
                  title={`チェック済み ${completedCount} 件を削除`}
                >完了済みを削除</button>
              )}
              <span>進捗 {progressPercent}%</span>
            </div>
            <span>{completedCount} / {todos.length} 完了</span>
          </div>
          <div className="progress-bar-track">
            <div className="progress-bar-fill" style={{ width: progressPercent + '%' }}></div>
          </div>
        </div>

        {notificationPermission === 'denied' && (
          <div className="notification-banner">
            バッジを表示するには、設定 › Safari › 通知 で許可してください
          </div>
        )}
      </div>

      <div className="todo-list">
        {todos.map(todo => (
          <div
            key={todo.id}
            className={`todo-item${todo.completed ? ' completed' : ''}`}
            onClick={() => openEditPanel(todo)}
          >
            <span onClick={e => e.stopPropagation()}>
              <input
                type="checkbox"
                checked={todo.completed}
                onChange={() => toggleTodo(todo.id)}
              />
            </span>
            <span className="todo-text">{todo.text}</span>
          </div>
        ))}
        {todos.length === 0 && !todosLoading && (
          <p className="empty-message">タスクがありません。＋ボタンで追加してください。</p>
        )}
      </div>

      <button className="fab" onClick={openAddPanel} aria-label="タスクを追加">
        <span className="fab-icon">＋</span>
      </button>

      {overlayVisible && (
        <div
          className="overlay fade-enter"
          onClick={showAddPanel ? closeAddPanel : closeEditPanel}
        ></div>
      )}

      {showAddPanel && (
        <div
          className={`add-panel${addSwipe.isSwipeClosing ? ' slide-up-leave' : ' slide-up-enter'}`}
          style={addSwipe.panelStyle}
          onTouchStart={addSwipe.onTouchStart}
          onTouchMove={addSwipe.onTouchMove}
          onTouchEnd={addSwipe.onTouchEnd}
        >
          <div className="add-panel-handle"></div>
          <div className="add-panel-header">
            <button className="close-btn" onClick={closeAddPanel} aria-label="閉じる">✕</button>
            <h2 className="add-panel-title">タスクを追加</h2>
          </div>
          <input
            value={newTodoText}
            onChange={e => setNewTodoText(e.target.value)}
            type="text"
            className="add-panel-input"
            placeholder="新しいタスクを入力..."
            autoFocus
          />
          <div className="add-panel-actions">
            <button className="add-btn" onClick={addTodo} disabled={newTodoText.trim() === ''}>追加</button>
          </div>
        </div>
      )}

      {showEditPanel && (
        <div
          className={`add-panel${editSwipe.isSwipeClosing ? ' slide-up-leave' : ' slide-up-enter'}`}
          style={editSwipe.panelStyle}
          onTouchStart={editSwipe.onTouchStart}
          onTouchMove={editSwipe.onTouchMove}
          onTouchEnd={editSwipe.onTouchEnd}
        >
          <div className="add-panel-handle"></div>
          <div className="add-panel-header">
            <button className="close-btn" onClick={closeEditPanel} aria-label="閉じる">✕</button>
            <h2 className="add-panel-title">タスクを編集</h2>
          </div>
          <input
            value={editTodoText}
            onChange={e => setEditTodoText(e.target.value)}
            type="text"
            className="add-panel-input"
            placeholder="タスクを入力..."
            autoFocus
          />
          <div className="add-panel-actions edit-panel-actions">
            <button className="delete-btn edit-delete-btn" onClick={deleteTodoAndClose}>削除</button>
            <button className="add-btn" onClick={updateTodo} disabled={editTodoText.trim() === ''}>保存</button>
          </div>
        </div>
      )}
    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { onAuthStateChanged, signOut, type User } from 'firebase/auth'
import {
  collection,
  addDoc,
  deleteDoc,
  updateDoc,
  doc,
  onSnapshot,
  query,
  orderBy,
  serverTimestamp
} from 'firebase/firestore'
import { auth, db } from './firebase'
import AuthForm from './components/AuthForm.vue'

interface TodoItem {
  id: string
  text: string
  completed: boolean
}

const currentUser = ref<User | null>(null)
const authLoading = ref(true)
const todos = ref<TodoItem[]>([])
const newTodoText = ref('')
const showAddPanel = ref(false)
const notificationPermission = ref<NotificationPermission | 'unsupported'>('unsupported')

const SWIPE_CLOSE_THRESHOLD = 100

// 追加パネル スワイプ用
const panelTranslateY = ref(0)
const isDragging = ref(false)
const isSwipeClosing = ref(false)
let dragStartY = 0

const addPanelStyle = computed(() => {
  if (isSwipeClosing.value) {
    return { transform: 'translateY(100%)' }
  }
  if (isDragging.value) {
    return { transform: `translateY(${panelTranslateY.value}px)`, transition: 'none' }
  }
  if (panelTranslateY.value > 0) {
    return { transform: `translateY(${panelTranslateY.value}px)` }
  }
  return {}
})

const onPanelTouchStart = (e: TouchEvent) => {
  dragStartY = e.touches[0].clientY
  panelTranslateY.value = 0
  isDragging.value = true
}

const onPanelTouchMove = (e: TouchEvent) => {
  if (!isDragging.value) return
  const delta = e.touches[0].clientY - dragStartY
  panelTranslateY.value = Math.max(0, delta)
}

const onPanelTouchEnd = () => {
  if (panelTranslateY.value > SWIPE_CLOSE_THRESHOLD) {
    isDragging.value = false
    isSwipeClosing.value = true
    setTimeout(() => {
      isSwipeClosing.value = false
      panelTranslateY.value = 0
      closeAddPanel()
    }, 300)
  } else {
    isDragging.value = false
    nextTick(() => { panelTranslateY.value = 0 })
  }
}

// 編集パネル用
const showEditPanel = ref(false)
const editingTodo = ref<TodoItem | null>(null)
const editTodoText = ref('')
const editPanelTranslateY = ref(0)
const isEditDragging = ref(false)
const isEditSwipeClosing = ref(false)
let editDragStartY = 0

const editPanelStyle = computed(() => {
  if (isEditSwipeClosing.value) {
    return { transform: 'translateY(100%)' }
  }
  if (isEditDragging.value) {
    return { transform: `translateY(${editPanelTranslateY.value}px)`, transition: 'none' }
  }
  if (editPanelTranslateY.value > 0) {
    return { transform: `translateY(${editPanelTranslateY.value}px)` }
  }
  return {}
})

const onEditPanelTouchStart = (e: TouchEvent) => {
  editDragStartY = e.touches[0].clientY
  editPanelTranslateY.value = 0
  isEditDragging.value = true
}

const onEditPanelTouchMove = (e: TouchEvent) => {
  if (!isEditDragging.value) return
  const delta = e.touches[0].clientY - editDragStartY
  editPanelTranslateY.value = Math.max(0, delta)
}

const onEditPanelTouchEnd = () => {
  if (editPanelTranslateY.value > SWIPE_CLOSE_THRESHOLD) {
    isEditDragging.value = false
    isEditSwipeClosing.value = true
    setTimeout(() => {
      isEditSwipeClosing.value = false
      editPanelTranslateY.value = 0
      closeEditPanel()
    }, 300)
  } else {
    isEditDragging.value = false
    nextTick(() => { editPanelTranslateY.value = 0 })
  }
}


let unsubscribeTodos: (() => void) | null = null

const completedCount = computed(() => todos.value.filter(t => t.completed).length)
const incompleteCount = computed(() => todos.value.filter(t => !t.completed).length)
const progressPercent = computed(() =>
  todos.value.length === 0 ? 0 : Math.round((completedCount.value / todos.value.length) * 100)
)

const updateBadge = (count: number) => {
  if ('setAppBadge' in navigator) {
    if (count > 0) {
      navigator.setAppBadge(count)
    } else {
      navigator.clearAppBadge()
    }
  }
}

watch(incompleteCount, updateBadge, { immediate: true })

const subscribeTodos = (uid: string) => {
  const todosRef = collection(db, 'users', uid, 'todos')
  const q = query(todosRef, orderBy('createdAt', 'asc'))
  unsubscribeTodos = onSnapshot(q, (snapshot) => {
    todos.value = snapshot.docs.map((doc) => ({
      id: doc.id,
      text: doc.data().text as string,
      completed: doc.data().completed as boolean,
    }))
  })
}

const addTodo = async () => {
  if (!currentUser.value || newTodoText.value.trim() === '') return
  const text = newTodoText.value.trim()
  closeAddPanel()
  await addDoc(collection(db, 'users', currentUser.value.uid, 'todos'), {
    text,
    completed: false,
    createdAt: serverTimestamp(),
  })
}

const deleteTodo = async (id: string) => {
  if (!currentUser.value) return
  await deleteDoc(doc(db, 'users', currentUser.value.uid, 'todos', id))
}

const openEditPanel = (todo: TodoItem) => {
  editingTodo.value = todo
  editTodoText.value = todo.text
  editPanelTranslateY.value = 0
  isEditDragging.value = false
  isEditSwipeClosing.value = false
  showEditPanel.value = true
}

const closeEditPanel = () => {
  showEditPanel.value = false
  editingTodo.value = null
  editTodoText.value = ''
  editPanelTranslateY.value = 0
  isEditDragging.value = false
}

const updateTodo = async () => {
  if (!currentUser.value || !editingTodo.value || editTodoText.value.trim() === '') return
  const id = editingTodo.value.id
  const text = editTodoText.value.trim()
  closeEditPanel()
  await updateDoc(doc(db, 'users', currentUser.value.uid, 'todos', id), { text })
}

const deleteTodoAndClose = async () => {
  if (!currentUser.value || !editingTodo.value) return
  const id = editingTodo.value.id
  closeEditPanel()
  await deleteTodo(id)
}

const deleteCompletedTodos = async () => {
  if (!currentUser.value) return
  const completed = todos.value.filter(t => t.completed)
  await Promise.all(
    completed.map(t => deleteDoc(doc(db, 'users', currentUser.value!.uid, 'todos', t.id)))
  )
}

const toggleTodo = async (id: string) => {
  if (!currentUser.value) return
  const todo = todos.value.find((t) => t.id === id)
  if (todo) {
    await updateDoc(doc(db, 'users', currentUser.value.uid, 'todos', id), {
      completed: !todo.completed,
    })
  }
}

const logout = async () => {
  showMenu.value = false
  await signOut(auth)
}

const showMenu = ref(false)
const menuRef = ref<HTMLElement | null>(null)

const toggleMenu = () => {
  showMenu.value = !showMenu.value
}

const closeMenu = () => {
  showMenu.value = false
}

const handleDocumentClick = (e: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(e.target as Node)) {
    closeMenu()
  }
}


const requestNotificationPermission = async () => {
  if (!('Notification' in window)) return
  if (Notification.permission === 'default') {
    const result = await Notification.requestPermission()
    notificationPermission.value = result
    if (result === 'granted') {
      updateBadge(incompleteCount.value)
    }
  } else {
    notificationPermission.value = Notification.permission
  }
}

const openAddPanel = () => {
  showAddPanel.value = true
  newTodoText.value = ''
  panelTranslateY.value = 0
  isDragging.value = false
  isSwipeClosing.value = false
}

const closeAddPanel = () => {
  showAddPanel.value = false
  newTodoText.value = ''
  panelTranslateY.value = 0
  isDragging.value = false
}

let unsubscribeAuth: (() => void) | null = null

onMounted(() => {
  document.addEventListener('click', handleDocumentClick)
  if ('Notification' in window) {
    notificationPermission.value = Notification.permission
  }
  unsubscribeAuth = onAuthStateChanged(auth, (user) => {
    currentUser.value = user
    authLoading.value = false

    if (unsubscribeTodos) {
      unsubscribeTodos()
      unsubscribeTodos = null
      todos.value = []
    }

    if (user) {
      subscribeTodos(user.uid)
      requestNotificationPermission()
    }
  })
})

onUnmounted(() => {
  document.removeEventListener('click', handleDocumentClick)
  unsubscribeAuth?.()
  unsubscribeTodos?.()
  if ('clearAppBadge' in navigator) navigator.clearAppBadge()
})
</script>

<template>
  <div v-if="authLoading" class="loading-screen">
    <div class="loading-spinner"></div>
  </div>

  <AuthForm v-else-if="!currentUser" />

  <div v-else class="todo-app">
    <!-- ヘッダー＋進捗をまとめてスティッキー固定 -->
    <div class="sticky-top">
      <header class="app-header">
        <h1>Todoリスト</h1>
        <div class="hamburger-menu" ref="menuRef">
          <button class="hamburger-btn" @click="toggleMenu" aria-label="メニューを開く" :aria-expanded="showMenu">
            <span class="hamburger-line"></span>
            <span class="hamburger-line"></span>
            <span class="hamburger-line"></span>
          </button>
          <Transition name="menu-fade">
            <div v-if="showMenu" class="menu-dropdown">
              <div class="menu-account">
                <span class="menu-account-email">{{ currentUser.email }}</span>
              </div>
              <div class="menu-divider"></div>
              <button class="menu-logout-btn" @click="logout">
                <svg class="menu-logout-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                  <polyline points="16 17 21 12 16 7"/>
                  <line x1="21" y1="12" x2="9" y2="12"/>
                </svg>
                ログアウト
              </button>
            </div>
          </Transition>
        </div>
      </header>

      <div class="progress-section">
        <div class="progress-labels">
          <div class="progress-labels-left">
            <button
              v-if="completedCount > 0"
              class="delete-completed-btn"
              @click="deleteCompletedTodos"
              :title="`チェック済み ${completedCount} 件を削除`"
            >完了済みを削除</button>
            <span>進捗 {{ progressPercent }}%</span>
          </div>
          <span>{{ completedCount }} / {{ todos.length }} 完了</span>
        </div>
        <div class="progress-bar-track">
          <div class="progress-bar-fill" :style="{ width: progressPercent + '%' }"></div>
        </div>
      </div>

      <div v-if="notificationPermission === 'denied'" class="notification-banner">
        バッジを表示するには、設定 › Safari › 通知 で許可してください
      </div>
    </div>

    <!-- タスクリスト -->
    <div class="todo-list">
      <div
        v-for="todo in todos"
        :key="todo.id"
        class="todo-item"
        :class="{ completed: todo.completed }"
        @click="openEditPanel(todo)"
      >
        <span @click.stop>
          <input
            type="checkbox"
            :checked="todo.completed"
            @change="toggleTodo(todo.id)"
          />
        </span>
        <span class="todo-text">{{ todo.text }}</span>
      </div>

      <p v-if="todos.length === 0" class="empty-message">
        タスクがありません。＋ボタンで追加してください。
      </p>
    </div>

    <!-- FAB（右下の丸ボタン） -->
    <button class="fab" @click="openAddPanel" aria-label="タスクを追加">
      <span class="fab-icon">＋</span>
    </button>

    <!-- オーバーレイ -->
    <Transition name="fade">
      <div
        v-if="(showAddPanel || showEditPanel) && !isSwipeClosing && !isEditSwipeClosing"
        class="overlay"
        @click="showAddPanel ? closeAddPanel() : closeEditPanel()"
      ></div>
    </Transition>


    <!-- 下からスライドするタスク追加パネル -->
    <Transition :name="isSwipeClosing ? '' : 'slide-up'">
      <div
        v-if="showAddPanel"
        class="add-panel"
        :style="addPanelStyle"
        @touchstart="onPanelTouchStart"
        @touchmove.prevent="onPanelTouchMove"
        @touchend="onPanelTouchEnd"
      >
        <div class="add-panel-handle"></div>
        <div class="add-panel-header">
          <button class="close-btn" @click="closeAddPanel" aria-label="閉じる">✕</button>
          <h2 class="add-panel-title">タスクを追加</h2>
        </div>
        <input
          v-model="newTodoText"
          type="text"
          class="add-panel-input"
          placeholder="新しいタスクを入力..."
          @keyup.enter="addTodo"
          autofocus
        />
        <div class="add-panel-actions">
          <button class="add-btn" @click="addTodo" :disabled="newTodoText.trim() === ''">追加</button>
        </div>
      </div>
    </Transition>

    <!-- 下からスライドするタスク編集パネル -->
    <Transition :name="isEditSwipeClosing ? '' : 'slide-up'">
      <div
        v-if="showEditPanel"
        class="add-panel"
        :style="editPanelStyle"
        @touchstart="onEditPanelTouchStart"
        @touchmove.prevent="onEditPanelTouchMove"
        @touchend="onEditPanelTouchEnd"
      >
        <div class="add-panel-handle"></div>
        <div class="add-panel-header">
          <button class="close-btn" @click="closeEditPanel" aria-label="閉じる">✕</button>
          <h2 class="add-panel-title">タスクを編集</h2>
        </div>
        <input
          v-model="editTodoText"
          type="text"
          class="add-panel-input"
          placeholder="タスクを入力..."
          @keyup.enter="updateTodo"
          autofocus
        />
        <div class="add-panel-actions edit-panel-actions">
          <button class="delete-btn edit-delete-btn" @click="deleteTodoAndClose">削除</button>
          <button class="add-btn" @click="updateTodo" :disabled="editTodoText.trim() === ''">保存</button>
        </div>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.loading-screen {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

.loading-spinner {
  width: 44px;
  height: 44px;
  border: 4px solid rgba(102, 126, 234, 0.2);
  border-top-color: #667eea;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.todo-app {
  width: 100%;
  max-width: 600px;
  margin: 0 auto;
  min-height: 100vh;
  position: relative;
  display: flex;
  flex-direction: column;
}

/* スティッキーまとめコンテナ（ヘッダー＋進捗） */
.sticky-top {
  position: sticky;
  top: 0;
  z-index: 10;
  background-color: #ffffff;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.08);
}

/* ヘッダー */
.app-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75em 1.2em;
  gap: 0.5em;
}

.app-header h1 {
  font-size: 1.3em;
  margin: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  flex-shrink: 1;
}

.hamburger-menu {
  position: relative;
  flex-shrink: 0;
}

.hamburger-btn {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 5px;
  width: 40px;
  height: 40px;
  background: none;
  border: none;
  cursor: pointer;
  padding: 0.4em;
  border-radius: 8px;
}

.hamburger-btn:hover {
  background-color: rgba(33, 53, 71, 0.06);
  border-color: transparent;
}

.hamburger-line {
  display: block;
  width: 22px;
  height: 2px;
  background-color: #213547;
  border-radius: 2px;
}

.menu-dropdown {
  position: absolute;
  top: calc(100% + 6px);
  right: 0;
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.12);
  min-width: 220px;
  z-index: 50;
  overflow: hidden;
}

.menu-account {
  padding: 0.9em 1em;
}

.menu-account-email {
  display: block;
  font-size: 0.88em;
  color: #213547;
  word-break: break-all;
  text-align: left;
  pointer-events: none;
  user-select: text;
}

.menu-divider {
  height: 1px;
  background: rgba(0, 0, 0, 0.08);
  margin: 0;
}

.menu-logout-btn {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 0.5em;
  text-align: left;
  background: none;
  border: none;
  padding: 0.85em 1em;
  font-size: 0.9em;
  color: #dc2626;
  cursor: pointer;
}

.menu-logout-btn:hover {
  background-color: #fee2e2;
  border-color: transparent;
}

.menu-logout-icon {
  width: 1em;
  height: 1em;
  flex-shrink: 0;
}

.menu-fade-enter-active,
.menu-fade-leave-active {
  transition: opacity 0.15s ease, transform 0.15s ease;
}

.menu-fade-enter-from,
.menu-fade-leave-to {
  opacity: 0;
  transform: translateY(-6px);
}

/* 進捗セクション */
.progress-section {
  padding: 0.6em 1.2em 0.8em;
  border-top: 1px solid rgba(0, 0, 0, 0.06);
}

.progress-labels {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 0.82em;
  color: rgba(33, 53, 71, 0.6);
  margin-bottom: 0.45em;
}

.progress-labels-left {
  display: flex;
  align-items: center;
  gap: 0.6em;
}

.delete-completed-btn {
  background-color: #fee2e2;
  color: #dc2626;
  border: none;
  padding: 0.2em 0.55em;
  font-size: 0.85em;
  border-radius: 5px;
  cursor: pointer;
  white-space: nowrap;
  line-height: 1.4;
}

.delete-completed-btn:hover {
  background-color: #fecaca;
}

.progress-bar-track {
  width: 100%;
  height: 6px;
  background-color: rgba(0, 0, 0, 0.08);
  border-radius: 3px;
  overflow: hidden;
}

.progress-bar-fill {
  height: 100%;
  background: #667eea;
  border-radius: 3px;
  transition: width 0.4s ease;
}

/* 通知拒否バナー */
.notification-banner {
  padding: 0.55em 1.2em;
  background: #fef9c3;
  color: #854d0e;
  font-size: 0.8em;
  text-align: center;
  border-top: 1px solid #fde047;
}

/* タスクリスト */
.todo-list {
  flex: 1;
  padding: 1em 1.2em;
  padding-bottom: 5em;
}

.todo-item {
  display: flex;
  align-items: center;
  gap: 1em;
  padding: 0.9em 1em;
  margin-bottom: 0.5em;
  background-color: #ffffff;
  border-radius: 10px;
  border: 1px solid rgba(0, 0, 0, 0.07);
  transition: background-color 0.15s, box-shadow 0.15s;
  cursor: pointer;
}

.todo-item:hover {
  background-color: #f8f8ff;
  box-shadow: 0 1px 6px rgba(102, 126, 234, 0.1);
}

.todo-item.completed .todo-text {
  text-decoration: line-through;
  opacity: 0.45;
}

.todo-text {
  flex: 1;
  text-align: left;
  color: #213547;
}

.delete-btn {
  background-color: #fee2e2;
  color: #dc2626;
  border: none;
  padding: 0.3em 0.65em;
  font-size: 0.82em;
  border-radius: 6px;
}

.delete-btn:hover {
  background-color: #fecaca;
  border-color: transparent;
}

.edit-panel-actions {
  justify-content: space-between;
}

.edit-delete-btn {
  padding: 0.6em 1.2em;
  font-size: 1em;
}

.empty-message {
  color: rgba(33, 53, 71, 0.4);
  font-style: italic;
  padding: 3em 1em;
  text-align: center;
}

/* FABボタン */
.fab {
  position: fixed;
  bottom: 2rem;
  right: 2rem;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: #667eea;
  border: none;
  box-shadow: 0 4px 16px rgba(102, 126, 234, 0.4);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 20;
  transition: transform 0.2s, box-shadow 0.2s;
  padding: 0;
}

.fab:hover {
  transform: scale(1.1);
  box-shadow: 0 6px 20px rgba(102, 126, 234, 0.55);
  border-color: transparent;
}

.fab-icon {
  font-size: 1.8em;
  line-height: 1;
  color: #fff;
  font-weight: 300;
}

/* オーバーレイ */
.overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.35);
  z-index: 30;
}

/* タスク追加パネル */
.add-panel {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: #ffffff;
  border-radius: 20px 20px 0 0;
  padding: 1em 1.5em 2em;
  z-index: 40;
  box-shadow: 0 -4px 24px rgba(0, 0, 0, 0.12);
  transition: transform 0.3s cubic-bezier(0.32, 0.72, 0, 1);
}

.add-panel-handle {
  width: 40px;
  height: 4px;
  background: rgba(0, 0, 0, 0.15);
  border-radius: 2px;
  margin: 0 auto 1.2em;
}

.add-panel-header {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  margin-bottom: 1em;
}

.close-btn {
  background: none;
  border: none;
  font-size: 1.4em;
  line-height: 1;
  cursor: pointer;
  color: rgba(33, 53, 71, 0.5);
  flex-shrink: 0;
  padding: 0.1em;
  justify-self: start;
}

.close-btn:hover {
  color: #213547;
  border-color: transparent;
}

.add-panel-title {
  font-size: 1.1em;
  margin: 0;
  text-align: center;
  color: #213547;
}

.add-panel-input {
  width: 100%;
  box-sizing: border-box;
  font-size: 1em;
  padding: 0.75em 1em;
  border-radius: 10px;
  border: 1px solid rgba(0, 0, 0, 0.15);
  background-color: #f9f9f9;
  color: #213547;
  margin-bottom: 1em;
}

.add-panel-input:focus {
  outline: none;
  border-color: #667eea;
  background-color: #ffffff;
}

.add-panel-actions {
  display: flex;
  gap: 0.75em;
  justify-content: flex-end;
}

.add-btn {
  background: #667eea;
  border: none;
  padding: 0.6em 1.5em;
  border-radius: 8px;
  color: #fff;
  font-weight: 600;
  cursor: pointer;
}

.add-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.add-btn:not(:disabled):hover {
  opacity: 0.88;
  border-color: transparent;
}

/* スライドアップトランジション */
.slide-up-enter-active,
.slide-up-leave-active {
  transition: transform 0.3s cubic-bezier(0.32, 0.72, 0, 1);
}

.slide-up-enter-from,
.slide-up-leave-to {
  transform: translateY(100%);
}

/* フェードトランジション */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
